### ISSUE TITLE
compileSdkVersion is 16

### ISSUE THREAD

**Issue by fingdo** [jgilfelt/chuck#44] opened 2017-04-19 02:18 UTC
my project compileSdkVersion is 14.when use change library compileSdkVersion to 14,the smaple project running normally.
Can you tell me why use compileSdkVersion 16?have some unpredictable bugs?

**Comment by jgilfelt** [comment] 2017-04-19 08:50
Dupe of #18, #20, #29

**Closed by jgilfelt** 2017-04-19 08:50 UTC
