### ISSUE TITLE
Using with Volley

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [jgilfelt/chuck#13] opened 2017-02-12 06:09 UTC
Hello
 I am using Volley in my project to handle webservices.Is it possible to use this library with Volley?
if answer is negative, can you recommend me another library that is adaptive with Volley?
thanks in advance.

**Comment by jgilfelt** [comment] 2017-02-12 10:33
Dupe of #5

**Closed by jgilfelt** 2017-02-12 10:33 UTC
